export default {
  empty_overview_title: 'No data yet',
  empty_overview_body: 'Save your first snapshot in the Entry tab — your stats will show up here.',
  empty_overview_cta: 'Go to Entry',
  data_as_of: (m) => `Data as of ${m}`,
  overview_option: 'Overview',
  allocation_title: 'Allocation',
  series_net: 'Net worth',
  net_worth_chart: 'Net worth',
  tags_label: 'Tags',
  view_by_category: 'By category',
  view_by_group: 'By group',
  no_tags_title: 'No tags yet',
  no_tags_body: 'Open an account in Settings and add tags like "investment" or "rental" to create cross-cutting groups.',
  no_groups_title: 'No groups yet',
  no_groups_body: 'Create groups in Settings to view accounts by tag combinations in Overview.',
  manage_groups: 'Manage groups',
};
