import { registerTranslations } from '../../../core/i18n/index.js';

registerTranslations('en', {
  id_col: 'ID',
  name_fr_col: 'Name (FR)',
  name_en_col: 'Name (EN)',
  category_col: 'Category',
  kind_col: 'Kind',
  owner_col: 'Owner',
  share_col: 'Share %',
  active_col: 'Active',
  order_col: 'Order',
  growth_rate_col: 'Growth rate (%/yr)',
  calculate_value: 'Calculate',
  account_type_label: 'Account type',
  add_account: '+ Add account',
  import_historical: 'Import historical data',
  import_hint: 'Paste your existing monthly tracking sheet (wide format: account names down the first column, months across the top). Copy/paste from Google Sheets works (tab-separated).',
  parse: 'Parse',
  clear: 'Clear',
  preview_label: 'Preview',
  source_row: 'Source row',
  sample_value: 'Sample value',
  map_to_account: 'Map to account',
  overwrite_toggle: 'Overwrite existing snapshots for the months in this paste (otherwise skip months already in the sheet)',
  import_btn: 'Import',
  import_placeholder: 'Paste CSV or TSV here…',
  migrate_title: 'Migrate Account ID',
  current_id_label: 'Current ID',
  new_account_type_label: 'New account type',
  new_id_label: 'New ID',
  confirm_rename: 'Confirm rename',
});
