import { registerTranslations } from '../../../core/i18n/index.js';

registerTranslations('fr', {
  id_col: 'ID',
  name_fr_col: 'Nom (FR)',
  name_en_col: 'Nom (EN)',
  category_col: 'Catégorie',
  kind_col: 'Type',
  owner_col: 'Propriétaire',
  share_col: 'Part %',
  active_col: 'Actif',
  order_col: 'Ordre',
  growth_rate_col: 'Croissance (%/an)',
  calculate_value: 'Calculer',
  account_type_label: 'Type de compte',
  add_account: '+ Ajouter un compte',
  import_historical: 'Importer des données historiques',
  import_hint: 'Collez votre feuille de suivi mensuelle (format large : comptes en colonne, mois en ligne). La copie depuis Google Sheets (TSV) fonctionne directement.',
  parse: 'Analyser',
  clear: 'Effacer',
  preview_label: 'Aperçu',
  source_row: 'Ligne source',
  sample_value: 'Valeur exemple',
  map_to_account: 'Associer au compte',
  overwrite_toggle: 'Écraser les bilans existants pour les mois de ce collage (sinon, ignorer les mois déjà dans la feuille)',
  import_btn: 'Importer',
  import_placeholder: 'Coller le CSV ou TSV ici…',
  migrate_title: "Migrer l'ID du compte",
  current_id_label: 'ID actuel',
  new_account_type_label: 'Nouveau type de compte',
  new_id_label: 'Nouvel ID',
  confirm_rename: 'Confirmer',
});
