export default {
  save_snapshot: 'Enregistrer le bilan',
  reload_from_sheet: 'Recharger',
  copy_prev_month: 'Copier le mois préc.',
  date_label: 'Date',
  day_comment: 'Commentaire du jour',
  copy_prev_day: 'Copier le jour préc.',
  copy_prev_entry: "Copier l'entrée préc.",
  reset_entry: 'Réinitialiser',
  comment_placeholder: 'Commentaire (facultatif)',
  month_comment_placeholder: 'Notes pour ce mois (facultatif)',
  existing_date: 'Date existante (édition)',
  new_date: 'Nouvelle date',
  owner_self: 'Vous',
  owner_partner: 'Conjoint',
  owner_joint: 'Joint',
  net_worth_fallback: 'Calculé avec la dernière valeur connue des comptes non saisis sur cette page.',
  confirm_reset_entry: 'Effacer toutes les valeurs saisies ?',
  confirm_delete_entries: 'Ces comptes avaient une valeur enregistrée pour cette date et seront supprimés :',
  confirm_delete_ok: 'Supprimer',
};
