import { registerTranslations } from '../../core/i18n/index.js';

registerTranslations('en', {
  tab_stock_options:     'Stock Options',
  opt_vested_label:      'Vested value',
  opt_unvested_label:    'Unvested (at current FMV)',
  opt_value_over_time:   'Options value over time',
  opt_add_company:       '+ Add company',
  opt_no_companies:      'No equity positions tracked',
  opt_no_companies_hint: 'Add a company to start tracking your stock options and RSUs.',
  opt_no_grants:         'No grants added',
  opt_add_grant:         '+ Add grant',
  opt_edit_company:      'Edit company',
  opt_log_fmv:           'Log FMV',
  opt_fmv_placeholder:   'Price per share',
  opt_note_placeholder:  'Note (optional)',
  opt_no_fmv:            'No FMV recorded',
  opt_last_fmv:          'FMV',
  opt_vested_shares_fmt: '{vested} / {total} shares vested',
  opt_fully_vested:      'Fully vested',
  opt_cliff_pending:     'Cliff in {months} month(s)',
  opt_company_name:      'Company name',
  opt_ticker:            'Ticker (optional)',
  opt_active:            'Active',
  opt_new_company:       'New company',
  opt_edit_company_title:'Edit company',
  opt_new_grant:         'New grant',
  opt_edit_grant:        'Edit grant',
  opt_grant_label:       'Label',
  opt_grant_type:        'Type',
  opt_grant_date:        'Grant date',
  opt_total_shares:      'Total shares',
  opt_strike_price:      'Strike price',
  opt_strike_hint:       '0 for RSUs',
  opt_vesting_start:     'Vesting start',
  opt_cliff_months:      'Cliff (months)',
  opt_vesting_months:    'Duration (months)',
  opt_vesting_interval:  'Vesting interval',
  opt_expiry_date:       'Expiry date (optional)',
  opt_interval_monthly:  'Monthly',
  opt_interval_quarterly:'Quarterly',
  opt_interval_annual:   'Annual',
  opt_delete_company:    'Delete company',
  opt_delete_grant:      'Delete grant',
  equity_label:          'Equity',
  opt_fmv_history:       'FMV History',
  opt_fmv_date_col:      'Date',
  opt_fmv_value_col:     'Price',
  opt_fmv_note_col:      'Note',
  opt_grants_label:      'Grants',
  opt_inactive:          'Inactive',
  edit_label:            'Edit',
  opt_fmv_add:           'Add FMV',
  opt_no_fmv_history:    'No FMV entries yet',
  opt_pill_vesting:      'Vesting',
  opt_pill_value:        'Value',
  opt_shares_vested:     'shares vested',
  opt_shares_unvested:   'shares unvested',
  opt_equity_tags:       'Equity tags',
  opt_equity_tags_hint:  'Comma-separated tags used to include equity in overview groups (e.g. tech, investments)',
});
