import { registerTranslations } from '../../core/i18n/index.js';

registerTranslations('fr', {
  tab_stock_options:     'Options sur actions',
  opt_vested_label:      'Valeur acquise',
  opt_unvested_label:    'Non acquis (au FMV actuel)',
  opt_value_over_time:   'Valeur des options dans le temps',
  opt_add_company:       '+ Ajouter entreprise',
  opt_no_companies:      'Aucune position en actions suivie',
  opt_no_companies_hint: 'Ajoutez une entreprise pour suivre vos options d\'achat et RSU.',
  opt_no_grants:         'Aucune attribution ajoutée',
  opt_add_grant:         '+ Ajouter attribution',
  opt_edit_company:      'Modifier l\'entreprise',
  opt_log_fmv:           'Saisir FMV',
  opt_fmv_placeholder:   'Prix par action',
  opt_note_placeholder:  'Note (optionnel)',
  opt_no_fmv:            'Aucun FMV enregistré',
  opt_last_fmv:          'FMV',
  opt_vested_shares_fmt: '{vested} / {total} actions acquises',
  opt_fully_vested:      'Entièrement acquis',
  opt_cliff_pending:     'Cliff dans {months} mois',
  opt_company_name:      'Nom de l\'entreprise',
  opt_ticker:            'Symbole boursier (optionnel)',
  opt_active:            'Actif',
  opt_new_company:       'Nouvelle entreprise',
  opt_edit_company_title:'Modifier l\'entreprise',
  opt_new_grant:         'Nouvelle attribution',
  opt_edit_grant:        'Modifier l\'attribution',
  opt_grant_label:       'Libellé',
  opt_grant_type:        'Type',
  opt_grant_date:        'Date d\'attribution',
  opt_total_shares:      'Nombre total d\'actions',
  opt_strike_price:      'Prix d\'exercice',
  opt_strike_hint:       '0 pour les RSU',
  opt_vesting_start:     'Début d\'acquisition',
  opt_cliff_months:      'Cliff (mois)',
  opt_vesting_months:    'Durée (mois)',
  opt_vesting_interval:  'Intervalle d\'acquisition',
  opt_expiry_date:       'Date d\'expiration (optionnel)',
  opt_interval_monthly:  'Mensuel',
  opt_interval_quarterly:'Trimestriel',
  opt_interval_annual:   'Annuel',
  opt_delete_company:    'Supprimer l\'entreprise',
  opt_delete_grant:      'Supprimer l\'attribution',
  equity_label:          'Équité',
  opt_fmv_history:       'Historique FMV',
  opt_fmv_date_col:      'Date',
  opt_fmv_value_col:     'Prix',
  opt_fmv_note_col:      'Note',
  opt_grants_label:      'Attributions',
  opt_inactive:          'Inactif',
  edit_label:            'Modifier',
  opt_fmv_add:           'Ajouter FMV',
  opt_no_fmv_history:    'Aucune entrée FMV',
  opt_equity_tags:       'Étiquettes equity',
  opt_equity_tags_hint:  'Étiquettes séparées par des virgules pour inclure les options dans les groupes (ex: tech, investissements)',
});
